package com.rize.rizeandroid.data

import com.rize.rizeandroid.data.entity.BenchSessionDetails
import com.rize.rizeandroid.data.entity.CurlSessionDetails
import com.rize.rizeandroid.data.entity.RepBenchDetails
import com.rize.rizeandroid.data.entity.RepCurlDetails
import com.rize.rizeandroid.data.entity.RepSquatDetails
import com.rize.rizeandroid.data.entity.SessionRep
import com.rize.rizeandroid.data.entity.SquatSessionDetails
import com.rize.rizeandroid.data.entity.WorkoutSession

/**
 * Snapshot completo de una rep antes de tener un session_id asignado. El
 * repository se encarga de cablear los IDs al insertar.
 */
data class PendingRep(
    val rep: SessionRep,                   // session_id se rellena al insertar
    val squatDetails: RepSquatDetails? = null,  // rep_id se rellena al insertar
    val curlDetails: RepCurlDetails? = null,
    val benchDetails: RepBenchDetails? = null
)

/**
 * Bundle con todo lo necesario para persistir una sesión completa. Se usa para
 * pasar datos entre CameraActivity y SummaryActivity (modo manual) y para
 * insertar en una sola transacción.
 *
 * `session.id` se ignora al insertar (autogenerated). Lo mismo para
 * `details.sessionId` que se rellena tras conocer el session_id real.
 */
data class PendingSessionData(
    val session: WorkoutSession,
    val squatDetails: SquatSessionDetails? = null,
    val curlDetails: CurlSessionDetails? = null,
    val benchDetails: BenchSessionDetails? = null,
    val reps: List<PendingRep>,
    val attemptedRepCount: Int = 0
)
